# Basic settings
title: "Convincible"
email: "contact@convincible.media"
#description: "Marketing and Communications &middot; Cambridge, UK"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.convincible.media"
#twitter_username: "BeConvincible"
#github_username:  "Convincible"

# Build settings
source: "source"
destination: "public"
sass_dir: "source/assets/styles"
markdown: "kramdown"

# show_drafts: null
# future: false
# unpublished: false
excerpt_separator: "\n\n"
strict_front_matter: true

# include: .htaccess
# exclude: 

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "base"

permalink: ":year/:month/:slug.html"

# Collections
collections:
  services:
    title: "Services"
    order: 1
    output: true
    permalink: ":collection/:slug.html"
  showcase:
    title: "Showcase"
    order: 2
    output: true
    permalink: ":collection/:slug.html"
  contact:
    title: "Contact"
    output: true
    permalink: ":collection/:slug.html"