# Basic settings
title: "Convincible"
email: "contact@convincible.media"
#description: "Marketing and Communications &middot; Cambridge, UK"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.convincible.media"
#twitter_username: "BeConvincible"
#github_username:  "Convincible"

# Build settings
source: "source"
destination: "public"
sass_dir: "source/assets/styles"

# show_drafts: null
# future: false
# unpublished: false
excerpt_separator: "\n\n"
strict_front_matter: true

include:
  - _redirects
# exclude:

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "base"

permalink: ":year/:month/:slug.html"

# Collections
collections:
  services:
    title: "Services"
    order: 1
    output: true
    permalink: ":slug.html"
  showcase:
    title: "Showcase"
    order: 2
    output: true
    permalink: "showcase/:slug.html"
  examples:
    title: "Examples"
    output: true
    permalink: "example/:slug.html"
  clients:
    title: "Clients"
    order: 3
    output: true
    permalink: "client/:slug.html"
  contact:
    title: "Contact"
    output: true
    permalink: "contact/:slug.html"
  articles:
    title: "Articles"
    output: true
    permalink: "article/:slug.html"


# Markdown
markdown:                      "kramdown"
kramdown:
   auto_id_prefix:             "section-"
   auto_ids:                   true
   auto_id_stripping:          true
   entity_output:              "symbolic"
   hard_wrap:                  false
   header_offset:              1
   smart_quotes:               "lsquo,rsquo,ldquo,rdquo"
   toc_levels:                 "1..2"
   transliterated_header_ids:  true
   html_to_native:             true
